-- TrailMate — persistent chat sessions. Run once in the Supabase SQL editor,
-- AFTER auth.sql (needs auth.users and the trips table).
--
-- Model: every conversation is a session. The "current chat" is the user's
-- newest session with no trip_id. Saving a trip stamps trip_id onto the
-- session that produced it — that is the ONLY way an old chat stays reachable
-- from the UI (there is deliberately no "all past chats" list). `itinerary`
-- holds the last presented-but-unsaved plan so a refresh restores it; it is
-- cleared when the trip is saved (the plan then lives in trips.data).

create table if not exists chat_sessions (
    id          text primary key,                -- nanoid generated by the app
    user_id     uuid not null references auth.users(id) on delete cascade,
    trip_id     text references trips(id) on delete set null,
    itinerary   jsonb,                           -- last presented, not-yet-saved plan
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);

create index if not exists chat_sessions_current
    on chat_sessions (user_id, updated_at desc) where trip_id is null;
create index if not exists chat_sessions_trip on chat_sessions (trip_id);

create table if not exists chat_messages (
    id          bigint generated always as identity primary key,
    session_id  text not null references chat_sessions(id) on delete cascade,
    role        text not null check (role in ('user', 'assistant')),
    content     text not null default '',
    created_at  timestamptz not null default now()
);

create index if not exists chat_messages_session on chat_messages (session_id, id);

-- RLS: sessions belong to their user; messages follow their session. The
-- server's user-facing reads/writes run on the request's RLS-bound client,
-- so Postgres enforces isolation (service_role bypasses for system tasks).
alter table chat_sessions enable row level security;
alter table chat_messages enable row level security;

drop policy if exists "chat_sessions_select_own" on chat_sessions;
drop policy if exists "chat_sessions_insert_own" on chat_sessions;
drop policy if exists "chat_sessions_update_own" on chat_sessions;
drop policy if exists "chat_sessions_delete_own" on chat_sessions;

create policy "chat_sessions_select_own" on chat_sessions for select using (auth.uid() = user_id);
create policy "chat_sessions_insert_own" on chat_sessions for insert with check (auth.uid() = user_id);
create policy "chat_sessions_update_own" on chat_sessions for update using (auth.uid() = user_id);
create policy "chat_sessions_delete_own" on chat_sessions for delete using (auth.uid() = user_id);

drop policy if exists "chat_messages_select_own" on chat_messages;
drop policy if exists "chat_messages_insert_own" on chat_messages;
drop policy if exists "chat_messages_delete_own" on chat_messages;

create policy "chat_messages_select_own" on chat_messages for select
    using (exists (select 1 from chat_sessions s where s.id = session_id and s.user_id = auth.uid()));
create policy "chat_messages_insert_own" on chat_messages for insert
    with check (exists (select 1 from chat_sessions s where s.id = session_id and s.user_id = auth.uid()));
create policy "chat_messages_delete_own" on chat_messages for delete
    using (exists (select 1 from chat_sessions s where s.id = session_id and s.user_id = auth.uid()));
