-- TrailMate — Supabase schema
-- Run this once in the Supabase SQL editor (Dashboard → SQL → New query).

-- Fuzzy/Hebrew-friendly text search.
create extension if not exists pg_trgm;

-- ── trails: the agent's searchable trail catalog (seeded from tiuli) ──────────
create table if not exists trails (
    id              integer primary key,        -- tiuli track id
    name_he         text not null,
    subtitle        text,
    slug            text,
    url             text,
    description_he  text,
    waze_link       text,
    lat             double precision,
    lng             double precision,
    difficulty      text,
    duration        text,
    trail_map_image text
);

-- Trigram indexes so ilike / similarity searches stay fast.
create index if not exists trails_name_trgm
    on trails using gin (name_he gin_trgm_ops);
create index if not exists trails_subtitle_trgm
    on trails using gin (subtitle gin_trgm_ops);
create index if not exists trails_desc_trgm
    on trails using gin (description_he gin_trgm_ops);
-- Bounding-box filtering for area queries.
create index if not exists trails_latlng on trails (lat, lng);

-- ── trips: saved itineraries, keyed by a shareable id (no auth) ──────────────
create table if not exists trips (
    id          text primary key,               -- nanoid generated by the app
    title       text not null,
    dates       text,
    data        jsonb not null,                 -- full itinerary JSON (days[])
    created_at  timestamptz not null default now()
);

-- Note on security: this app has no auth yet. The server (Next.js route
-- handlers) talks to Supabase with the service_role key only. Do NOT expose
-- that key to the browser. Row Level Security is therefore left disabled;
-- when auth is added, enable RLS and scope trips to the owner.
